### ISSUE TITLE
请求增加 ATCoder 比赛提醒

### ISSUE THREAD

**Issue by d0j1a1701** [mqnu00/koishi-plugin-not-just-cf#1]

**Comment by mqnu00** [comment]
ok，我有时间看看

**Comment by mqnu00** [comment]
有atcoder contest api吗

**Comment by d0j1a1701** [comment]
https://github.com/kenkoooo/AtCoderProblems/blob/master/doc/api.md

**Comment by mqnu00** [comment]
> https://github.com/kenkoooo/AtCoderProblems/blob/master/doc/api.md

你指的是[kenkoooo.com/atcoder/resources/contests.json](https://kenkoooo.com/atcoder/resources/contests.json)吗
我发现这里面存在的都是过去的比赛，没有未来的

**Comment by snowf14k3** [comment]
> https://github.com/kenkoooo/AtCoderProblems/blob/master/doc/api.md

山东理工的 https://contests.sdutacm.cn/contests.json
