### ISSUE TITLE
比赛时间错误，提前了八个小时。

### ISSUE THREAD

**Issue by ouyu69** [mqnu00/koishi-plugin-not-just-cf#2]
比赛时间错误，提前了八个小时。
![图片](https://github.com/user-attachments/assets/8a5a5d91-c60f-41c0-80d2-4ecf5214e404)

**Comment by mqnu00** [comment]
我本地没有这个问题，你可以检查一下服务器的时区之类的和时间相关的，或者有没有梯子

**Comment by mqnu00** [comment]
还有看一下其他OJ有没有这个问题

**Comment by mqnu00** [comment]
没有问题的话这个issue我就关了

**Comment by ouyu69** [comment]
没问题了，我忘改docker的时间了
